<?php

namespace Database\Factories;

use Closure;
use Illuminate\Database\Eloquent\Factories\Factory;

class AuhorFactory extends Factory
{
  /**
   * Define the model's default state.
   *
   * @return array
   */
  public function definition()
  {
    return [
        //
      ];
  }
  public function afterCreating(Closure $callback)
  {
    return parent::afterCreating($callback); // TODO: Change the autogenerated stub
  }
}
