<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class BlogPostFactory extends Factory
{
  /**
   * Define the model's default state.
   *
   * @return array
   */
  public function definition()
  {
    return [
      'title' => $this->faker->realTextBetween(20, 30),
      'content' => $this->faker->realTextBetween(400, 5000),
      'created_at' => $this->faker->dateTimeBetween('-3 months'),
    ];
  }
  public function state($state)
  {
    return parent::state($state); // TODO: Change the autogenerated stub
  }

  public function Test()
  {
    return $this->state(function (array $attributes) {
      return [
        'title' => 'New Title',
      ];
    });
  }
}
